reference: ../../data/ref/hg19.ucsc.fa

datasets:
  # Tumor-Normal cell-line data from Illumina Basespace
  HCC22118C-vs-HCC22118BL:
    tumor: "bams/HCC22118C-vs-HCC22118BL/tumor.bam"
    normal: "bams/HCC22118C-vs-HCC22118BL/normal.bam"
    aligner: "default"
  HCC1187C-vs-HCC1187BL:
    tumor: "bams/HCC1187C-vs-HCC1187BL/tumor.bam"
    normal: "bams/HCC1187C-vs-HCC1187BL/normal.bam" 
    aligner: "default"


params:
  dkfz:
    platypus: "--genIndels=1 --genSNPs=1 --maxReads=10000000"
    sm_caller: "-m 112.0 -s 14.826 -r 0.01332338 -y 0.00001 -e 0.0310 -E 0.2138"
  assemble:
    platypus: "--genIndels=1 --genSNPs=1 --maxReads=10000000 --assemble=1"
    sm_caller: "-m 112.0 -s 14.826 -r 0.01332338 -y 0.00001 -e 0.0310 -E 0.2138"
